### ISSUE TITLE
EXEMPLO COM FACADE (error)

### ISSUE THREAD

**Issue by willph** [wppconnect-team/wppconnect-laravel-client#3]
```
.......
            if($response['status'] == 'Success'):
                Session::put('token', $response['token']);
                Session::put('session', $response['session']);
            endif;
....
```

No codigo acima, na linha ` if($response['status'] == 'Success'):` o retorno de `$response['status']` é `success`, fazendo com que apresente erro.
eu corrigir colocando `success` e funcionou tranquilo.

**Comment by bgastaldi** [comment]
Corrigido. 

Obrigado
